# -*- coding: utf-8 -*-
"""Competitors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikuKxxkQHK57odVhkj4Rh-2a5CHHSZTf
"""

import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse

def find_competitors(keyword):
    query = keyword.replace(" ", "+")
    url = f"https://www.google.com/search?q={query}"

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
    }

    # Make a request to Google
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print("Error: Could not retrieve results.")
        return

    # Parse the HTML
    soup = BeautifulSoup(response.text, "html.parser")

    # Find all result URLs
    competitors = []
    for result in soup.find_all("div", class_="tF2Cxc"):
        link = result.find("a", href=True)
        if link:
            domain = urlparse(link["href"]).netloc
            title = result.find("h3").text if result.find("h3") else "No title"
            competitors.append({"title": title, "url": link["href"], "domain": domain})

    # Display results
    # print("Top Competitors for Keyword:", keyword)
    for competitor in competitors:
        # print(f"Title: {competitor['title']}")
        # print(f"URL: {competitor['url']}")
        print({competitor['url']})
        # print(f"Domain: {competitor['domain']}\n")

# Use the function
find_competitors("What Does a Phoenix Symbolize Spiritually?")
#replace your keywords